[package]
name = "log-parser-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
regex = "1.11.1"
clap = { version = "4.5.38", features = ["derive"] }
anyhow = "1.0.98"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
